name: Support

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  Linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Cargo run tests
      run: cargo run tests/main.nys
  Windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Cargo run tests
      run: cargo run tests/main.nys
  Mac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Cargo run tests
      run: cargo run tests/main.nys

